export const shopActionTypes = {
  FETCH_COLLECTIONS_START: "[SHOP] FETCH_COLLECTIONS_START",
  FETCH_COLLECTIONS_SUCCESS: "[SHOP] FETCH_COLLECTIONS_SUCCESS",
  FETCH_COLLECTIONS_ERROR: "[SHOP] FETCH_COLLECTIONS_ERROR",
};
